spring:
  application:
    name: roll-dice
  jmx:
    default-domain: roll-dice
  main:
    allow-bean-definition-overriding: true
    allow-circular-references: true
  mvc:
    throw-exception-if-no-handler-found: true
  resources:
    add-mappings: false
  banner.location: classpath:banner.txt

# =============================================================================================
# = SERVICE
# =============================================================================================
service:
  properties:
    short-code: ROLL-DICE
    version: v1.0
    game-win: 25
server:
  port : 8080
  servlet:
    context-path: /roll-dice